#!/usr/bin/env python3
"""
index_clients.py — keep the clients/ folder self-documenting.

Scans clients/<company>/ folders plus the CRM store (prospects.json) and
regenerates:
    clients/INDEX.md            — master table of every prospect/client
    clients/<company>/README.md — per-prospect home page + file manifest

Run it any time after adding a company, an audit, a proposal, or a deliverable:

    python3 scripts/index_clients.py

Pure stdlib — no dependencies, no API keys.
"""

import json
import re
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLIENTS = ROOT / "clients"
CRM = CLIENTS / "_crm-data" / "prospects.json"
SUBFOLDERS = ["audits", "proposals", "reports", "deliverables", "inputs"]
NOW = datetime.now().strftime("%Y-%m-%d %H:%M")

# ---------------------------------------------------------------------------
# Manifest helpers (inline — avoids sys.path gymnastics for a standalone script)
# ---------------------------------------------------------------------------

def _load_manifest(client_folder: Path) -> dict:
    """Load manifest.json for a client folder, returning {} on missing/corrupt."""
    path = client_folder / "manifest.json"
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except (json.JSONDecodeError, UnicodeDecodeError):
        return {}


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")


def load_crm() -> list[dict]:
    if not CRM.exists():
        return []
    with open(CRM) as f:
        return json.load(f)


def match_record(folder: str, crm: list[dict]) -> dict | None:
    """Match a client folder to its CRM record by company slug or domain stem."""
    for p in crm:
        domain_stem = (p.get("domain") or "").split(".")[0]
        if folder in (p.get("folder", ""), slugify(p.get("company", "")), slugify(domain_stem)):
            return p
    return None


def list_files(folder: Path, sub: str) -> list[Path]:
    d = folder / sub
    if not d.exists():
        return []
    return sorted(f for f in d.iterdir() if f.is_file() and not f.name.startswith("."))


def fmt_eur(v) -> str:
    return f"€{v:,.0f}" if v else "—"


def write_readme(folder: Path, rec: dict | None) -> dict:
    name = folder.name
    title = (rec or {}).get("company") or name.replace("-", " ").title()
    lines = [f"# {title}", "", f"_Auto-generated by `scripts/index_clients.py` · {NOW}_", ""]

    # CRM snapshot
    if rec:
        lines += [
            "## CRM Snapshot",
            "",
            f"- **Domain:** {rec.get('domain') or '—'}",
            f"- **Status:** {rec.get('status') or '—'}",
            f"- **GEO Score:** {rec.get('geo_score') if rec.get('geo_score') is not None else '—'}/100",
            f"- **Monthly value:** {fmt_eur(rec.get('monthly_value'))}",
            f"- **Industry:** {rec.get('industry') or '—'}",
            f"- **Country:** {rec.get('country') or '—'}",
            f"- **Contact:** {rec.get('contact_name') or '—'} {('<' + rec['contact_email'] + '>') if rec.get('contact_email') else ''}".rstrip(),
            f"- **Audit date:** {rec.get('audit_date') or '—'}",
            "",
        ]
    else:
        lines += ["## CRM Snapshot", "", "> ⚠️ Not yet tracked in the CRM (`prospects.json`). Add via the web app or `/geo prospect`.", ""]

    # Load manifest once for this client
    manifest = _load_manifest(folder)

    # File manifest
    lines += ["## Files", ""]
    total = 0
    for sub in SUBFOLDERS:
        files = list_files(folder, sub)
        total += len(files)
        if not files:
            continue
        lines.append(f"### {sub}/")
        for f in files:
            tag = " (→ link)" if f.is_symlink() else ""
            entry = manifest.get(f.name)
            if entry:
                file_title = entry.get("title") or f.name
                ftype = entry.get("file_type", "")
                desc = entry.get("description", "")
                purpose = entry.get("purpose", "")
                audience = entry.get("audience", "")
                header = f"- **`{f.name}`**{tag}"
                if ftype:
                    header += f" — {ftype}"
                lines.append(header)
                if file_title and file_title != f.name:
                    lines.append(f"  - *{file_title}*")
                if desc:
                    lines.append(f"  - {desc}")
                if purpose:
                    lines.append(f"  - **Purpose:** {purpose}")
                if audience:
                    lines.append(f"  - **Audience:** {audience}")
            else:
                lines.append(f"- `{f.name}`{tag}")
        lines.append("")
    if total == 0:
        lines += ["_No files yet._", ""]

    (folder / "README.md").write_text("\n".join(lines))
    return {
        "folder": name,
        "title": title,
        "rec": rec,
        "file_count": total,
        "deliverables": len(list_files(folder, "deliverables")),
    }


def write_index(summaries: list[dict]):
    lines = [
        "# Client / Prospect Index",
        "",
        f"_Auto-generated by `scripts/index_clients.py` · {NOW}_",
        "",
        "One folder per company under `clients/`. The live visual view is the web app (port 5050).",
        "",
        "| Company | Folder | Status | Score | Monthly | Deliverables | Files |",
        "|---------|--------|--------|-------|---------|--------------|-------|",
    ]
    for s in sorted(summaries, key=lambda x: x["title"].lower()):
        r = s["rec"] or {}
        lines.append(
            f"| {s['title']} | [`{s['folder']}/`](./{s['folder']}/) "
            f"| {r.get('status') or '—'} "
            f"| {r.get('geo_score') if r.get('geo_score') is not None else '—'} "
            f"| {fmt_eur(r.get('monthly_value'))} "
            f"| {s['deliverables']} | {s['file_count']} |"
        )
    lines += ["", f"**Totals:** {len(summaries)} companies · "
              f"{sum(s['deliverables'] for s in summaries)} deliverables.", ""]
    (CLIENTS / "INDEX.md").write_text("\n".join(lines))


def main():
    crm = load_crm()
    folders = sorted(
        d for d in CLIENTS.iterdir()
        if d.is_dir() and not d.name.startswith("_")
    )
    summaries = [write_readme(f, match_record(f.name, crm)) for f in folders]
    write_index(summaries)
    print(f"✓ Indexed {len(summaries)} client folder(s) → clients/INDEX.md")
    for s in summaries:
        flag = "" if s["rec"] else "  ⚠️ no CRM record"
        print(f"  · {s['folder']}: {s['file_count']} files, {s['deliverables']} deliverables{flag}")


if __name__ == "__main__":
    main()
